version: '3.8'

services:
  # MySQL 資料庫
  mysql:
    image: mysql:8.0
    container_name: Pulse_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # 開發用密碼
      MYSQL_DATABASE: Pulse_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  # Redis 快取與 Pub/Sub
  redis:
    image: redis:alpine
    container_name: Pulse_redis
    restart: always
    ports:
      - "16379:6379"

volumes:
  mysql_data: